apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-springboot
  namespace: sk-team-06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-springboot
  template:
    metadata:
      labels:
        app: backend-springboot
    spec:
      containers:
        - name: backend-springboot
          image: seyoon93/backend-springboot:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
        
          args:
            - --spring.profiles.active=prod
