spring:
  datasource:
    url: jdbc:mysql://mariadb:3306/test_auto #host.docker.internal:3306
    username: skala_user
    password: skalapass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://mongodb:27017/test_auto # host.docker.internal:27017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
